# Generated by Django 2.2.13 on 2021-01-05 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='drejtimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drejtimi', models.CharField(max_length=255)),
                ('JoSygjerim', models.ManyToManyField(blank=True, related_name='JoSygjerim', to=settings.AUTH_USER_MODEL)),
                ('sygjerime', models.ManyToManyField(blank=True, related_name='sygjerime', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='drejtimetEfakultetit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('id_Drejtimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumi.drejtimet')),
            ],
        ),
        migrations.CreateModel(
            name='Komunat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komuna', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri_Lenda', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lendet_Drejtimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestri', models.IntegerField(choices=[(1, 'Semestri 1'), (2, 'Semestri 2'), (3, 'Semestri 3'), (4, 'Semestri 4'), (5, 'Semestri 5'), (6, 'Semestri 6'), (7, 'Semestri 7'), (8, 'Semestri 8')], default=1)),
                ('Drejtimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumi.drejtimetEfakultetit')),
                ('id_Lenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumi.Lenda')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
                ('permbajtja', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('data_postimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('autori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_Lenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumi.Lendet_Drejtimit')),
                ('id_drejtmi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumi.drejtimetEfakultetit')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fakulteti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=255)),
                ('Fakultet', models.IntegerField(choices=[(2, 'Privat'), (1, 'Publik')], default=1)),
                ('Logo', models.ImageField(null=True, upload_to='')),
                ('komuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumi.Komunat')),
            ],
        ),
        migrations.AddField(
            model_name='drejtimetefakultetit',
            name='id_fakultetit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumi.fakulteti'),
        ),
    ]
