# Generated by Django 2.2.13 on 2021-01-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(1, 'Publik'), (2, 'Privat')], default=1),
        ),
    ]
