# Generated by Django 2.2.13 on 2021-01-06 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumi', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postimet',
        ),
    ]
