# Generated by Django 2.2.13 on 2021-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0006_auto_20210106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(1, 'Publik'), (2, 'Privat')], default=1),
        ),
    ]
