# Generated by Django 3.1.5 on 2021-01-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0023_auto_20210116_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_postimi',
            new_name='postimi',
        ),
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(2, 'Privat'), (1, 'Publik')], default=1),
        ),
    ]
