# Generated by Django 3.0.5 on 2021-01-24 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0028_auto_20210124_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergjigjje',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 13, 31, 5, 490984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 13, 31, 5, 490455, tzinfo=utc)),
        ),
    ]
