# Generated by Django 3.0.5 on 2021-01-25 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0030_auto_20210124_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(1, 'Publik'), (2, 'Privat')], default=1),
        ),
        migrations.AlterField(
            model_name='pergjigjje',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 19, 15, 16, 576559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 19, 15, 16, 575588, tzinfo=utc)),
        ),
    ]
