# Generated by Django 3.0.5 on 2021-01-26 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumi', '0034_auto_20210126_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(1, 'Publik'), (2, 'Privat')], default=1),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='autori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
