# Generated by Django 3.0.5 on 2021-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0036_auto_20210126_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(1, 'Publik'), (2, 'Privat')], default=1),
        ),
        migrations.AlterField(
            model_name='pergjigjje',
            name='pergjigja',
            field=models.TextField(max_length=1000),
        ),
    ]
