# Generated by Django 3.0.5 on 2021-01-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0038_auto_20210126_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergjigjje',
            name='pyetje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumi.pyetje'),
        ),
    ]
