# Generated by Django 3.0.5 on 2021-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumi', '0040_auto_20210126_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakulteti',
            name='Fakultet',
            field=models.IntegerField(choices=[(2, 'Privat'), (1, 'Publik')], default=1),
        ),
    ]
