# Generated by Django 2.2.13 on 2021-01-05 09:53

import biblotekaOnline.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioName', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('audio', models.FileField(upload_to='documents/%Y/%m/%d', validators=[biblotekaOnline.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=255)),
                ('Mbiemri', models.CharField(max_length=255)),
                ('Biografia', models.TextField()),
                ('Profili', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GrupMosha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrupMosha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Klasifikimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasifikimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Librat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emriLibrit', models.CharField(max_length=50, null=True)),
                ('Permbajtja', models.TextField(default='', max_length=1000)),
                ('sasia', models.IntegerField(default=1)),
                ('copertina', models.ImageField(blank=True, default='download.jpg', null=True, upload_to='Photo', validators=[biblotekaOnline.validators.validImg])),
                ('Pdf', models.FileField(blank=True, default='download.jpg', null=True, upload_to='files', validators=[biblotekaOnline.validators.validPdf])),
                ('dataVendosjes', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Autori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblotekaOnline.Autori')),
            ],
        ),
        migrations.CreateModel(
            name='Zhandri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhandri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shtoZhandrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Libri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblotekaOnline.Librat')),
                ('id_Zhadri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblotekaOnline.Zhandri')),
            ],
        ),
        migrations.AddField(
            model_name='librat',
            name='Zhandri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblotekaOnline.Zhandri'),
        ),
        migrations.AddField(
            model_name='librat',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
