# Generated by Django 3.1.5 on 2021-01-08 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblotekaOnline', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='librat',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
    ]
