# Generated by Django 3.1.5 on 2021-01-10 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblotekaOnline', '0004_auto_20210108_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librat',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
